# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'plan-it-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for plan-it-ios
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'SPStorkController'
  pod 'GCCalendar'
  pod 'IQKeyboardManagerSwift'
  pod 'Haptica'
  pod 'Hero'
  pod 'SVProgressHUD'
  pod 'FSCalendar'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'GooglePlacesSearchController'

end
