# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'plan-it-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for plan-it-ios
  pod 'Firebase/Core'

end
